# Generated by Django 3.1.3 on 2022-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20221027_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuser',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productuser',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
