# Generated by Django 3.1.3 on 2022-10-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221028_0549'),
    ]

    operations = [
    ]
